# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190510_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
