# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190510_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='music_name',
            field=models.ManyToManyField(to='music.Music_info'),
        ),
    ]
