# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=255, verbose_name='国籍')),
                ('detail', models.TextField(blank=True, max_length=3000, verbose_name='详情')),
                ('img', models.ImageField(default=None, null=True, upload_to='avatar')),
                ('name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='music.Music_info', verbose_name='姓名')),
            ],
        ),
    ]
