# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singers',
            name='name',
            field=models.CharField(max_length=255, verbose_name='姓名'),
        ),
    ]
