# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190508_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=255, verbose_name='音乐名')),
                ('author', models.CharField(max_length=255, verbose_name='歌手')),
                ('music_img', models.ImageField(default=None, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='My_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=255, verbose_name='音乐名')),
                ('author', models.CharField(max_length=255, verbose_name='歌手')),
                ('music_img', models.ImageField(default=None, null=True, upload_to='images')),
            ],
        ),
    ]
