# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_favorite_user_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_favorite',
            name='music_img',
        ),
        migrations.RemoveField(
            model_name='my_list',
            name='music_img',
        ),
    ]
