# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-12 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190512_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_list',
            name='music_id',
            field=models.IntegerField(verbose_name='歌曲'),
        ),
    ]
